In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
%matplotlib inline

In [2]:
df_Train=pd.read_csv('Agriculture.csv')
df_Test=pd.read_csv('testing1.csv')

In [3]:
df_Train.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000001                      188          1          0   
1  F00000003                      209          1          0   
2  F00000004                      257          1          0   
3  F00000005                      257          1          1   
4  F00000006                      342          1          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                0.0   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   

   Number_Weeks_Quit  Season  Crop_Damage  
0                  0       1            0  
1                  0       2            1  
2                  0       2            1  
3                  0       2            1  
4                  0       2            1

In [4]:
df_Test.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000002                      188          1          1   
1  F00000007                      410          1          1   
2  F00000011                      626          1          0   
3  F00000013                      731          1          0   
4  F00000014                      789          0          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                NaN   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   

   Number_Weeks_Quit  Season  
0                  0       2  
1                  0       2  
2                  0       2  
3                  0       2  
4                  0       1

In [5]:
print(df_Train.shape)
print(df_Test.shape)

(88858, 10)
(59310, 9)


In [6]:
df_Train.isnull().sum()

ID                            0
Estimated_Insects_Count       0
Crop_Type                     0
Soil_Type                     0
Pesticide_Use_Category        0
Number_Doses_Week             0
Number_Weeks_Used          9000
Number_Weeks_Quit             0
Season                        0
Crop_Damage                   0
dtype: int64

In [7]:
df_Test.isnull().sum()

ID                            0
Estimated_Insects_Count       0
Crop_Type                     0
Soil_Type                     0
Pesticide_Use_Category        0
Number_Doses_Week             0
Number_Weeks_Used          5893
Number_Weeks_Quit             0
Season                        0
dtype: int64

In [964]:
df1=pd.read_csv('NewAgriTrain.csv')
df2=pd.read_csv('NewAgriTest.csv')

In [965]:
df1.shape, df2.shape

((88858, 10), (59310, 9))

In [966]:
df_Big=df1.append(df2,sort=False)
df_Big.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0   1                      188          1          0                       1   
1   3                      209          1          0                       1   
2   4                      257          1          0                       1   
3   5                      257          1          1                       1   
4   6                      342          1          0                       1   

   Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                  0                0.0                  0       1   
1                  0                0.0                  0       2   
2                  0                0.0                  0       2   
3                  0                0.0                  0       2   
4                  0                0.0                  0       2   

   Crop_Damage  
0          0.0  
1          1.0  
2          1.0  
3          1.0  
4          1.0

In [967]:
df_Big.isnull().sum()

ID                             0
Estimated_Insects_Count        0
Crop_Type                      0
Soil_Type                      0
Pesticide_Use_Category         0
Number_Doses_Week              0
Number_Weeks_Used          14893
Number_Weeks_Quit              0
Season                         0
Crop_Damage                59310
dtype: int64

In [968]:
df_Big['Number_Weeks_Used'].value_counts()

20.0    6523
30.0    6348
25.0    5206
40.0    4634
15.0    4099
        ... 
63.0      79
64.0      63
65.0      58
66.0      30
67.0      13
Name: Number_Weeks_Used, Length: 64, dtype: int64

In [969]:
df_Big['Number_Weeks_Used'].unique()

array([ 0., nan, 26., 20., 15., 14., 19., 24.,  8., 23., 25., 28., 29.,
       22., 21., 17., 30., 35., 32., 27., 16., 31., 33., 34., 39., 38.,
       42., 40., 41., 36., 44., 37., 46., 45., 47., 43., 50., 10., 49.,
       53., 48., 51., 54., 52., 55., 56., 61., 18., 57., 62., 60., 63.,
       66., 59., 64., 13.,  7.,  5., 12.,  6.,  9., 58., 11., 65., 67.])

In [970]:
df_Big['Number_Weeks_Used']=df_Big['Number_Weeks_Used'].fillna(10.0)

In [971]:
df_Big['Number_Weeks_Used'].unique()

array([ 0., 10., 26., 20., 15., 14., 19., 24.,  8., 23., 25., 28., 29.,
       22., 21., 17., 30., 35., 32., 27., 16., 31., 33., 34., 39., 38.,
       42., 40., 41., 36., 44., 37., 46., 45., 47., 43., 50., 49., 53.,
       48., 51., 54., 52., 55., 56., 61., 18., 57., 62., 60., 63., 66.,
       59., 64., 13.,  7.,  5., 12.,  6.,  9., 58., 11., 65., 67.])

In [972]:
df_Big.isnull().sum()

ID                             0
Estimated_Insects_Count        0
Crop_Type                      0
Soil_Type                      0
Pesticide_Use_Category         0
Number_Doses_Week              0
Number_Weeks_Used              0
Number_Weeks_Quit              0
Season                         0
Crop_Damage                59310
dtype: int64

In [973]:
df_Big.dtypes

ID                           int64
Estimated_Insects_Count      int64
Crop_Type                    int64
Soil_Type                    int64
Pesticide_Use_Category       int64
Number_Doses_Week            int64
Number_Weeks_Used          float64
Number_Weeks_Quit            int64
Season                       int64
Crop_Damage                float64
dtype: object

In [974]:
df_Big.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0   1                      188          1          0                       1   
1   3                      209          1          0                       1   
2   4                      257          1          0                       1   
3   5                      257          1          1                       1   
4   6                      342          1          0                       1   

   Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                  0                0.0                  0       1   
1                  0                0.0                  0       2   
2                  0                0.0                  0       2   
3                  0                0.0                  0       2   
4                  0                0.0                  0       2   

   Crop_Damage  
0          0.0  
1          1.0  
2          1.0  
3          1.0  
4          1.0

In [975]:
df_Big.dtypes

ID                           int64
Estimated_Insects_Count      int64
Crop_Type                    int64
Soil_Type                    int64
Pesticide_Use_Category       int64
Number_Doses_Week            int64
Number_Weeks_Used          float64
Number_Weeks_Quit            int64
Season                       int64
Crop_Damage                float64
dtype: object

In [976]:
df_Big['Crop_Damage']=df_Big['Crop_Damage'].fillna(0.0)

In [977]:
df_Big['Crop_Damage']=df_Big['Crop_Damage'].astype(int)

In [978]:
df_Big.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0   1                      188          1          0                       1   
1   3                      209          1          0                       1   
2   4                      257          1          0                       1   
3   5                      257          1          1                       1   
4   6                      342          1          0                       1   

   Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                  0                0.0                  0       1   
1                  0                0.0                  0       2   
2                  0                0.0                  0       2   
3                  0                0.0                  0       2   
4                  0                0.0                  0       2   

   Crop_Damage  
0            0  
1            1  
2            1  
3            1  
4            1

In [979]:
df_Big['Crop_Damage'].unique()

array([0, 1, 2])

In [980]:
df_Big['Crop_Damage'].value_counts()

0    133548
1     12307
2      2313
Name: Crop_Damage, dtype: int64

In [981]:
print(df_Train.shape)
print(df_Test.shape)

(88858, 10)
(59310, 9)


In [982]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()

#columns_to_scale = ['ID','Estimated_Insects_Count']
#df_Big[columns_to_scale] = sc.fit_transform(df_Big[columns_to_scale])

In [983]:
df_Big.shape

(148168, 10)

In [1084]:
df_Big.drop('ID', axis=1, inplace=True)

In [1085]:
df_train=df_Big[0:88858]
df_test=df_Big[88858:]

In [1086]:
print(df_train.shape)
print(df_test.shape)

(88858, 9)
(59310, 9)


In [1087]:
df_test.drop('Crop_Damage', axis=1, inplace=True)

D:\anaconda\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [1088]:
print(df_train.shape)
print(df_test.shape)

(88858, 9)
(59310, 8)


In [1089]:
df_train['Crop_Damage'].value_counts()

0    74238
1    12307
2     2313
Name: Crop_Damage, dtype: int64

In [1090]:
X=df_train.drop(['Crop_Damage'],axis=1)
y=df_train[['Crop_Damage']]

In [1091]:
y.head()

Crop_Damage
0            0
1            1
2            1
3            1
4            1

In [1092]:
X.head()

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                      188          1          0                       1   
1                      209          1          0                       1   
2                      257          1          0                       1   
3                      257          1          1                       1   
4                      342          1          0                       1   

   Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  
0                  0                0.0                  0       1  
1                  0                0.0                  0       2  
2                  0                0.0                  0       2  
3                  0                0.0                  0       2  
4                  0                0.0                  0       2

In [1249]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.202107,random_state=7)

In [1250]:
import lightgbm as lgb
clf = lgb.LGBMClassifier(max_depth=-2, min_child_samples=28, n_estimators=365,
                         num_leaves=16, learning_rate=0.07592)
clf.fit(X_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.07592, max_depth=-2,
               min_child_samples=28, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=365, n_jobs=-1, num_leaves=16, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [1251]:
pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))

0.8490450470516175
[[14786   225     1]
 [ 2026   462     0]
 [  304   155     0]]


In [1252]:
prediction = clf.predict(df_test)
prediction

array([1, 1, 1, ..., 0, 0, 0])

In [1253]:
result = prediction.ravel() 
result

array([1, 1, 1, ..., 0, 0, 0])

In [1254]:
output = pd.DataFrame({'ID': df_Test.ID, 'Crop_Damage': result})
output.to_csv('AgriHack5.csv', index=False)